name: Build & Publish Container

on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # build-and-push-image:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     packages: write

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3

  #     - name: Login to GitHub Container Registry
  #       uses: docker/login-action@v2
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}

  #     - name: "Build image: ${{ github.repository }}"
  #       run: docker build . -f Dockerfile -t $REGISTRY/$IMAGE_NAME

  #     - name: Push ${{ github.repository }} to GitHub container registry
  #       run: |
  #         docker push $REGISTRY/$IMAGE_NAME:latest

  #     - name: DockerHub Login
  #       env: 
  #         DOCKER_USERNAME: ${{ github.actor }}
  #         DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  #       run: |
  #         docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

  #     - name: Push ${{ github.repository }} to DockerHub Container registry
  #       run: |
  #         docker tag $REGISTRY/$IMAGE_NAME:latest $IMAGE_NAME:latest
  #         docker push $IMAGE_NAME

  deploy-webapp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - name: Azure CLI script file
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az --version

